# Generated by Django 5.2.6 on 2025-09-10 20:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, help_text='Users that this user follows', related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
