# Generated by Django 5.2.4 on 2025-08-14 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0003_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('can_add_book', 'Can add book'), ('can_change_book', 'Can change book'), ('can_delete_book', 'Can delete book'), ('can_view', 'Can view books'), ('can_create', 'Can create books'), ('can_edit', 'Can edit books'), ('can_delete', 'Can delete books'))},
        ),
    ]
