# Generated by Django 5.2.6 on 2025-09-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply_to',
            field=models.TextField(blank=True, help_text='Optional reply to another comment', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(blank=True, help_text='Optional summary of the post', null=True),
        ),
    ]
